service: stock-alarms

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs8.10
  timeout: 1
  versionFunctions: false
  environment: ${file(./serverless.env.yml)}

custom:
  alerts:
    topics:
      alarm:
        topic: ${self:service}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: ${file(serverless.env.yml):RECIPIENT_EMAIL, env:RECIPIENT_EMAIL}
    alarms:
      - functionErrors

functions:
  stock-alarms:
    handler: src/index.run
    timeout: 1
    events:
      - schedule: rate(1 day)

plugins:
  - serverless-plugin-aws-alerts
